services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dmitryd\DdDeepl\:
    resource: '../Classes/*'

  Dmitryd\DdDeepl\Command\ManageDeeplGlossariesCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary'
        description: 'Uploads, downloads, lists, or deletes DeepL glossaries using account settings in the current TYPO3 version'
        hidden: false
        schedulable: false

  Dmitryd\DdDeepl\Hook\DataHandlerTranslationHook:
    public: true

  cache.deepl_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', "getCache"]
    arguments: ["dd_deepl"]

  Dmitryd\DdDeepl\Service\DeeplTranslationService:
    arguments:
      - "@cache.deepl_cache"