services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dmitryd\DdDeepl\:
    resource: '../Classes/*'

  Dmitryd\DdDeepl\Command\ManageDeeplGlossariesCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary'
        description: 'Uploads, downloads, lists, or deletes DeepL glossaries using account settings in the current TYPO3 version'
        hidden: false
        schedulable: false

  Dmitryd\DdDeepl\Service\DeeplTranslationService:
    arguments:
      $runtimeCache: '@cache.runtime'
      $deepLLocalizationScope: '@Dmitryd\DdDeepl\Localization\DeepLLocalizationScope'

  Dmitryd\DdDeepl\Localization\DeepLLocalizationHandler:
    autoconfigure: false
    tags:
      - name: 'backend.localization.handler'
        priority: 100

  TYPO3\CMS\Backend\Controller\Wizard\LocalizationController:
    arguments:
      $localizationHandler: '@TYPO3\CMS\Backend\Localization\ManualLocalizationHandler'

  Dmitryd\DdDeepl\Hook\DataHandlerTranslationHook:
    public: true
