services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Dmitryd\DdDeepl\:
    resource: '../Classes/*'

  Dmitryd\DdDeepl\Command\ManageDeeplGlossariesCommand:
    tags:
      - name: 'console.command'
        command: 'deepl:glossary'
        description: 'Uploads, downloads, lists, or deletes DeepL glossaries using account settings in the current TYPO3 version'
        hidden: false
        schedulable: false

  Dmitryd\DdDeepl\Hook\DataHandlerTranslationHook:
    public: true
